// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Room struct {
	ID       int64
	Name     string
	Password string
}

type User struct {
	ID       int64
	Username string
}
