// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Room struct {
	ID               int64
	Name             string
	Password         string
	CurrentlyPlaying *int64
}

type RoomHistory struct {
	RoomID  *int64
	VideoID *int64
}

type Video struct {
	ID    int64
	Uri   string
	Local bool
}
